type MonacoType = typeof import("monaco-editor");

export const EDITOR_THEME_BY_UI_THEME = {
  dawn: "agents-dawn",
  sepia: "agents-sepia",
  ember: "agents-ember",
  slate: "agents-slate",
  midnight: "agents-midnight",
  cobalt: "agents-cobalt",
  neon: "agents-neon",
  forest: "agents-forest",
  matrix: "agents-matrix",
  synthwave: "agents-synthwave",
  quantum: "agents-quantum",
} as const;

export type CodeEditorThemeId = (typeof EDITOR_THEME_BY_UI_THEME)[keyof typeof EDITOR_THEME_BY_UI_THEME];

type SyntaxPalette = {
  foreground: string;
  comment: string;
  keyword: string;
  operator: string;
  string: string;
  number: string;
  type: string;
  functionName: string;
  variable: string;
  tag: string;
  attribute: string;
  invalid: string;
};

type EditorThemePalette = SyntaxPalette & {
  base: "vs" | "vs-dark";
  background: string;
  lineHighlight: string;
  border: string;
  subtleBorder: string;
  gutter: string;
  lineNumber: string;
  activeLineNumber: string;
  selection: string;
  inactiveSelection: string;
  selectionHighlight: string;
  findMatch: string;
  findHighlight: string;
  cursor: string;
  widgetBackground: string;
  hoverBackground: string;
  inputBackground: string;
  scrollbar: string;
  scrollbarHover: string;
  inserted: string;
  deleted: string;
};

const THEME_PALETTES: Record<CodeEditorThemeId, EditorThemePalette> = {
  "agents-dawn": {
    base: "vs",
    background: "#f3ead6",
    foreground: "#2d2116",
    lineHighlight: "#e8dcc4",
    border: "#cbb994",
    subtleBorder: "#ded0b1",
    gutter: "#eee4cd",
    lineNumber: "#8c765c",
    activeLineNumber: "#5f452d",
    selection: "#b8d6e8",
    inactiveSelection: "#d5c8ad",
    selectionHighlight: "#d9e9ef",
    findMatch: "#e7bf67",
    findHighlight: "#ecdca5",
    cursor: "#7a4d27",
    widgetBackground: "#f6eddc",
    hoverBackground: "#fbf4e7",
    inputBackground: "#eadfc9",
    scrollbar: "#b8a98680",
    scrollbarHover: "#a8956eaa",
    inserted: "#6aa87830",
    deleted: "#c86a5f28",
    comment: "#7a6c58",
    keyword: "#8f5532",
    operator: "#74583a",
    string: "#587d44",
    number: "#896ab0",
    type: "#4f7f83",
    functionName: "#6e6aa8",
    variable: "#2d2116",
    tag: "#8b5b39",
    attribute: "#6c715f",
    invalid: "#b8473d",
  },
  "agents-sepia": {
    base: "vs",
    background: "#efe0c3",
    foreground: "#2a1c12",
    lineHighlight: "#e2cfab",
    border: "#b99a70",
    subtleBorder: "#d2bc98",
    gutter: "#e8d6b6",
    lineNumber: "#8d7153",
    activeLineNumber: "#5f3e24",
    selection: "#b6d0dc",
    inactiveSelection: "#d0bc98",
    selectionHighlight: "#dacda9",
    findMatch: "#d59f48",
    findHighlight: "#ead39b",
    cursor: "#8f5f37",
    widgetBackground: "#f4e6cb",
    hoverBackground: "#faedda",
    inputBackground: "#e1ccaa",
    scrollbar: "#a9875f80",
    scrollbarHover: "#92704daa",
    inserted: "#5e946530",
    deleted: "#b04c4328",
    comment: "#7c664f",
    keyword: "#9a5138",
    operator: "#6e533b",
    string: "#4f7c4d",
    number: "#7d68a1",
    type: "#497b76",
    functionName: "#5d679f",
    variable: "#2a1c12",
    tag: "#8f5f37",
    attribute: "#78683f",
    invalid: "#b04c43",
  },
  "agents-ember": {
    base: "vs-dark",
    background: "#1b1612",
    foreground: "#f3e8d1",
    lineHighlight: "#2b241d",
    border: "#5b4935",
    subtleBorder: "#3a3026",
    gutter: "#201a15",
    lineNumber: "#8d7a61",
    activeLineNumber: "#d2a566",
    selection: "#6c5437",
    inactiveSelection: "#453727",
    selectionHighlight: "#3c3023",
    findMatch: "#966f33",
    findHighlight: "#604821",
    cursor: "#f1c57b",
    widgetBackground: "#241e19",
    hoverBackground: "#2d241a",
    inputBackground: "#2b241d",
    scrollbar: "#6d594080",
    scrollbarHover: "#8b704faa",
    inserted: "#8fbc8a30",
    deleted: "#e0837628",
    comment: "#a69578",
    keyword: "#e39f6e",
    operator: "#d9bd8f",
    string: "#a8c982",
    number: "#d6a5d8",
    type: "#7db9a2",
    functionName: "#e0bf79",
    variable: "#f3e8d1",
    tag: "#e19b73",
    attribute: "#ceb16e",
    invalid: "#ff9185",
  },
  "agents-slate": {
    base: "vs-dark",
    background: "#131820",
    foreground: "#e3e7ec",
    lineHighlight: "#202932",
    border: "#3b4653",
    subtleBorder: "#2a333d",
    gutter: "#171d24",
    lineNumber: "#7f8b99",
    activeLineNumber: "#9bafc4",
    selection: "#42566c",
    inactiveSelection: "#2c3947",
    selectionHighlight: "#293543",
    findMatch: "#826b33",
    findHighlight: "#504526",
    cursor: "#dbe7f3",
    widgetBackground: "#1a2128",
    hoverBackground: "#232c36",
    inputBackground: "#202932",
    scrollbar: "#63738680",
    scrollbarHover: "#7c8fa5aa",
    inserted: "#8ab79330",
    deleted: "#dc808028",
    comment: "#8f9baa",
    keyword: "#d8939f",
    operator: "#c2ccd7",
    string: "#a4c67b",
    number: "#c5a6e8",
    type: "#73a9a1",
    functionName: "#9bb8e3",
    variable: "#e3e7ec",
    tag: "#e09aa6",
    attribute: "#d1b675",
    invalid: "#ff8f8f",
  },
  "agents-midnight": {
    base: "vs-dark",
    background: "#0d0f12",
    foreground: "#e1e0dd",
    lineHighlight: "#1c1f24",
    border: "#343942",
    subtleBorder: "#24272e",
    gutter: "#111317",
    lineNumber: "#747983",
    activeLineNumber: "#aab2bf",
    selection: "#3b4655",
    inactiveSelection: "#262c35",
    selectionHighlight: "#242a33",
    findMatch: "#76673b",
    findHighlight: "#494026",
    cursor: "#f3f2f0",
    widgetBackground: "#16181c",
    hoverBackground: "#1a1d22",
    inputBackground: "#1c1f24",
    scrollbar: "#5a606b80",
    scrollbarHover: "#747b87aa",
    inserted: "#86b58e30",
    deleted: "#de7c7c28",
    comment: "#8f949d",
    keyword: "#d98c9a",
    operator: "#c5c8ce",
    string: "#9fbd80",
    number: "#c1a5e0",
    type: "#73a59f",
    functionName: "#95acd0",
    variable: "#e1e0dd",
    tag: "#dc96a2",
    attribute: "#cdb478",
    invalid: "#ff8d8d",
  },
  "agents-cobalt": {
    base: "vs-dark",
    background: "#08111d",
    foreground: "#dce8f8",
    lineHighlight: "#132132",
    border: "#244463",
    subtleBorder: "#1a2d44",
    gutter: "#0b1624",
    lineNumber: "#6f8aa8",
    activeLineNumber: "#78b7ff",
    selection: "#234d78",
    inactiveSelection: "#17304a",
    selectionHighlight: "#142a40",
    findMatch: "#7c652f",
    findHighlight: "#4d4122",
    cursor: "#9fd0ff",
    widgetBackground: "#0f1a28",
    hoverBackground: "#142236",
    inputBackground: "#132132",
    scrollbar: "#42699180",
    scrollbarHover: "#5a86b4aa",
    inserted: "#81bea230",
    deleted: "#e17f8828",
    comment: "#7e9abb",
    keyword: "#78b7ff",
    operator: "#a9c6e5",
    string: "#9cd67f",
    number: "#d0a8ff",
    type: "#5ec0bf",
    functionName: "#ffd178",
    variable: "#dce8f8",
    tag: "#8fc2ff",
    attribute: "#f2c66d",
    invalid: "#ff8f99",
  },
  "agents-neon": {
    base: "vs-dark",
    background: "#05070f",
    foreground: "#d7fff8",
    lineHighlight: "#0f1730",
    border: "#205666",
    subtleBorder: "#163546",
    gutter: "#080d18",
    lineNumber: "#5f8a9a",
    activeLineNumber: "#2cf9ff",
    selection: "#123e54",
    inactiveSelection: "#102a3b",
    selectionHighlight: "#112a38",
    findMatch: "#85662b",
    findHighlight: "#503e22",
    cursor: "#2cf9ff",
    widgetBackground: "#0b1222",
    hoverBackground: "#121b32",
    inputBackground: "#0f1730",
    scrollbar: "#2cf9ff50",
    scrollbarHover: "#2cf9ff88",
    inserted: "#68f5b230",
    deleted: "#ff668a28",
    comment: "#6d93a2",
    keyword: "#d558ff",
    operator: "#8eefff",
    string: "#68f5b2",
    number: "#ffc660",
    type: "#56f3c8",
    functionName: "#6b8bff",
    variable: "#d7fff8",
    tag: "#2cf9ff",
    attribute: "#ff7fd0",
    invalid: "#ff668a",
  },
  "agents-forest": {
    base: "vs-dark",
    background: "#0a110d",
    foreground: "#d4e8db",
    lineHighlight: "#172820",
    border: "#284933",
    subtleBorder: "#1d3326",
    gutter: "#0d1711",
    lineNumber: "#6f967d",
    activeLineNumber: "#7bb89a",
    selection: "#244a34",
    inactiveSelection: "#183024",
    selectionHighlight: "#1a2f23",
    findMatch: "#7c6a2f",
    findHighlight: "#4d4322",
    cursor: "#a8e0ba",
    widgetBackground: "#111e17",
    hoverBackground: "#162218",
    inputBackground: "#172820",
    scrollbar: "#4d765980",
    scrollbarHover: "#65956eaa",
    inserted: "#78c68c30",
    deleted: "#da786e28",
    comment: "#7a9c87",
    keyword: "#86d98d",
    operator: "#b8d5c1",
    string: "#c6c878",
    number: "#c1a0db",
    type: "#5cbfa3",
    functionName: "#7bb89a",
    variable: "#d4e8db",
    tag: "#8ccf97",
    attribute: "#d0b678",
    invalid: "#ff8a80",
  },
  "agents-matrix": {
    base: "vs-dark",
    background: "#030704",
    foreground: "#d7f7dc",
    lineHighlight: "#0f1f16",
    border: "#2e6f45",
    subtleBorder: "#1b3e28",
    gutter: "#07110a",
    lineNumber: "#5fa66d",
    activeLineNumber: "#39ff88",
    selection: "#164c2a",
    inactiveSelection: "#102b1a",
    selectionHighlight: "#112a1a",
    findMatch: "#72722a",
    findHighlight: "#44441e",
    cursor: "#39ff88",
    widgetBackground: "#09140d",
    hoverBackground: "#0d1a11",
    inputBackground: "#0f1f16",
    scrollbar: "#39ff8855",
    scrollbarHover: "#39ff8888",
    inserted: "#39ff8830",
    deleted: "#ff6f6328",
    comment: "#6fa47a",
    keyword: "#8affc1",
    operator: "#b9ffc9",
    string: "#d7db73",
    number: "#d98b57",
    type: "#7bf4d3",
    functionName: "#39ff88",
    variable: "#d7f7dc",
    tag: "#8affc1",
    attribute: "#d7db73",
    invalid: "#ff6f63",
  },
  "agents-synthwave": {
    base: "vs-dark",
    background: "#10071a",
    foreground: "#f4e9ff",
    lineHighlight: "#28163c",
    border: "#6c3e82",
    subtleBorder: "#3a234e",
    gutter: "#160b22",
    lineNumber: "#8f73ad",
    activeLineNumber: "#ff71ce",
    selection: "#4a2864",
    inactiveSelection: "#301d43",
    selectionHighlight: "#281b3a",
    findMatch: "#8a5e28",
    findHighlight: "#533b22",
    cursor: "#ff71ce",
    widgetBackground: "#1b1029",
    hoverBackground: "#231234",
    inputBackground: "#28163c",
    scrollbar: "#ff71ce55",
    scrollbarHover: "#ff71ce88",
    inserted: "#72f1b830",
    deleted: "#ff6f9128",
    comment: "#9f86bd",
    keyword: "#ff71ce",
    operator: "#2de2e6",
    string: "#72f1b8",
    number: "#ffb86b",
    type: "#01cdfe",
    functionName: "#b967ff",
    variable: "#f4e9ff",
    tag: "#2de2e6",
    attribute: "#ffd166",
    invalid: "#ff6f91",
  },
  "agents-quantum": {
    base: "vs-dark",
    background: "#061016",
    foreground: "#e1f7f3",
    lineHighlight: "#142b34",
    border: "#315a60",
    subtleBorder: "#203a43",
    gutter: "#091820",
    lineNumber: "#729a9d",
    activeLineNumber: "#8ee6d8",
    selection: "#1f4a52",
    inactiveSelection: "#18323a",
    selectionHighlight: "#17323a",
    findMatch: "#7e652c",
    findHighlight: "#4b3f24",
    cursor: "#8ee6d8",
    widgetBackground: "#0d2028",
    hoverBackground: "#102731",
    inputBackground: "#142b34",
    scrollbar: "#8ee6d855",
    scrollbarHover: "#8ee6d888",
    inserted: "#7ee0a630",
    deleted: "#ff7c8a28",
    comment: "#7da6a4",
    keyword: "#c3a5ff",
    operator: "#b5ebe4",
    string: "#f0c36a",
    number: "#e791a9",
    type: "#9ad4ff",
    functionName: "#8ee6d8",
    variable: "#e1f7f3",
    tag: "#9ad4ff",
    attribute: "#f0c36a",
    invalid: "#ff7c8a",
  },
};

let didRegister = false;

function themeData(palette: EditorThemePalette): import("monaco-editor").editor.IStandaloneThemeData {
  return {
    base: palette.base,
    inherit: true,
    rules: [
      { token: "", foreground: palette.foreground },
      { token: "comment", foreground: palette.comment, fontStyle: "italic" },
      { token: "keyword", foreground: palette.keyword },
      { token: "keyword.control", foreground: palette.keyword },
      { token: "operator", foreground: palette.operator },
      { token: "string", foreground: palette.string },
      { token: "string.key.json", foreground: palette.attribute },
      { token: "number", foreground: palette.number },
      { token: "regexp", foreground: palette.number },
      { token: "type", foreground: palette.type },
      { token: "class", foreground: palette.type },
      { token: "interface", foreground: palette.type },
      { token: "enum", foreground: palette.type },
      { token: "namespace", foreground: palette.type },
      { token: "function", foreground: palette.functionName },
      { token: "function.call", foreground: palette.functionName },
      { token: "method", foreground: palette.functionName },
      { token: "variable", foreground: palette.variable },
      { token: "variable.predefined", foreground: palette.keyword },
      { token: "constant", foreground: palette.number },
      { token: "constant.language", foreground: palette.keyword },
      { token: "property", foreground: palette.attribute },
      { token: "tag", foreground: palette.tag },
      { token: "metatag", foreground: palette.tag },
      { token: "attribute.name", foreground: palette.attribute },
      { token: "attribute.value", foreground: palette.string },
      { token: "delimiter", foreground: palette.operator },
      { token: "delimiter.html", foreground: palette.operator },
      { token: "invalid", foreground: palette.invalid },
    ],
    colors: {
      "focusBorder": palette.border,
      "foreground": palette.foreground,
      "descriptionForeground": palette.lineNumber,
      "errorForeground": palette.invalid,
      "editor.background": palette.background,
      "editor.foreground": palette.foreground,
      "editorLineNumber.foreground": palette.lineNumber,
      "editorLineNumber.activeForeground": palette.activeLineNumber,
      "editorGutter.background": palette.gutter,
      "editorCursor.foreground": palette.cursor,
      "editor.lineHighlightBackground": palette.lineHighlight,
      "editor.lineHighlightBorder": palette.subtleBorder,
      "editor.selectionBackground": palette.selection,
      "editor.inactiveSelectionBackground": palette.inactiveSelection,
      "editor.selectionHighlightBackground": palette.selectionHighlight,
      "editor.wordHighlightBackground": palette.selectionHighlight,
      "editor.wordHighlightStrongBackground": palette.inactiveSelection,
      "editor.findMatchBackground": palette.findMatch,
      "editor.findMatchHighlightBackground": palette.findHighlight,
      "editor.findRangeHighlightBackground": palette.selectionHighlight,
      "editor.hoverHighlightBackground": palette.selectionHighlight,
      "editorBracketMatch.background": palette.selectionHighlight,
      "editorBracketMatch.border": palette.activeLineNumber,
      "editorIndentGuide.background1": palette.subtleBorder,
      "editorIndentGuide.activeBackground1": palette.border,
      "editorWhitespace.foreground": palette.subtleBorder,
      "editorRuler.foreground": palette.subtleBorder,
      "editorWidget.background": palette.widgetBackground,
      "editorWidget.foreground": palette.foreground,
      "editorWidget.border": palette.border,
      "editorHoverWidget.background": palette.hoverBackground,
      "editorHoverWidget.foreground": palette.foreground,
      "editorHoverWidget.border": palette.border,
      "editorSuggestWidget.background": palette.widgetBackground,
      "editorSuggestWidget.foreground": palette.foreground,
      "editorSuggestWidget.border": palette.border,
      "editorSuggestWidget.selectedBackground": palette.lineHighlight,
      "editorSuggestWidget.highlightForeground": palette.activeLineNumber,
      "editorStickyScroll.background": palette.background,
      "editorStickyScrollHover.background": palette.lineHighlight,
      "input.background": palette.inputBackground,
      "input.foreground": palette.foreground,
      "input.border": palette.border,
      "dropdown.background": palette.widgetBackground,
      "dropdown.foreground": palette.foreground,
      "dropdown.border": palette.border,
      "list.hoverBackground": palette.lineHighlight,
      "list.activeSelectionBackground": palette.selectionHighlight,
      "list.activeSelectionForeground": palette.foreground,
      "list.focusBackground": palette.selectionHighlight,
      "scrollbarSlider.background": palette.scrollbar,
      "scrollbarSlider.hoverBackground": palette.scrollbarHover,
      "scrollbarSlider.activeBackground": palette.scrollbarHover,
      "diffEditor.insertedTextBackground": palette.inserted,
      "diffEditor.removedTextBackground": palette.deleted,
      "peekView.border": palette.border,
      "peekViewEditor.background": palette.background,
      "peekViewResult.background": palette.widgetBackground,
      "peekViewTitle.background": palette.hoverBackground,
    },
  };
}

export function registerCodeEditorThemes(monaco: MonacoType): void {
  if (didRegister) return;
  for (const [themeId, palette] of Object.entries(THEME_PALETTES) as [CodeEditorThemeId, EditorThemePalette][]) {
    monaco.editor.defineTheme(themeId, themeData(palette));
  }
  didRegister = true;
}
